/* Generated by Yosys 0.7 (git sha1 61f6811, i686-w64-mingw32.static-gcc 4.9.3 -Os) */

(* top =  1  *)
(* src = "hw6\\q2\\a.v:1" *)
module adder_a_synth(a, b, ci, sum, co);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "hw6\\q2\\a.v:1" *)
  input a;
  (* src = "hw6\\q2\\a.v:1" *)
  input b;
  (* src = "hw6\\q2\\a.v:1" *)
  input ci;
  (* src = "hw6\\q2\\a.v:1" *)
  output co;
  (* src = "hw6\\q2\\a.v:1" *)
  output sum;
  NOT _12_ (
    .A(b),
    .Y(_08_)
  );
  NOT _13_ (
    .A(a),
    .Y(_09_)
  );
  NOT _14_ (    ///////
    .A(ci),
    .Y(_10_)
  );
  NAND _15_ (       //////
    .A(_10_),
    .B(_09_),
    .Y(_11_)
  );
  NAND _16_ (       //////
    .A(ci),
    .B(a),
    .Y(_00_)
  );
  NAND _17_ (     /////////
    .A(_00_),
    .B(_11_),
    .Y(_01_)
  );
  NOR _18_ (    ////////
    .A(_01_),
    .B(_08_),
    .Y(_02_)
  );
  NOR _19_ (    ///////
    .A(ci),
    .B(a),
    .Y(_03_)
  );
  NOR _20_ (   ////////
    .A(_10_),
    .B(_09_),
    .Y(_04_)
  );
  NOR _21_ (    ////////////
    .A(_04_),
    .B(_03_),
    .Y(_05_)
  );
  NOR _22_ (      ////////////
    .A(_05_),
    .B(b),
    .Y(_06_)
  );
  NOR _23_ (         ///////////
    .A(_06_),
    .B(_02_),
    .Y(sum)
  );
  NAND _24_ (    //////////
    .A(_05_),
    .B(b),
    .Y(_07_)
  );
  NAND _25_ ( /////////////////
    .A(_07_),
    .B(_00_),
    .Y(co)
  );
endmodule
